### PR TITLE
Version2.1

### PR DESCRIPTION
**Pull request by kogir**
I think this will work to bring caching back.  There's more I'd like to do, but this is loads better than nothing.

Let me know if you don't like the way I've done it, or you'd like it to be configured differently.

### CODE REVIEW

**Comment by kogir** [comment]
This one definitely needs thorough review.  I'm going to try and write some better tests and maybe even some benchmarks, but I made caching rather complicated.  I think it needed to be, but I'd love to be wrong.  Any and all feedback is welcome.

**Comment by grumpydev** [comment]
Well the file based one isn't thread safe for starters.

**Comment by kogir** [comment]
Well, by itself no, but as used in the CachingPipeline I think it is.
Didn't want to write all the locking code in both cache
implementations. Was there something specific I missed? Don't have the
code in front of me now but I might have forgotten cache write locking
for invalidation. I'll check that.

I'll improve the cache interface documentation to reflect my thread
access assumptions.

-Nick

Sent from my phone. Please forgive terse responses and autocorrect disasters.

On Jan 18, 2012, at 2:03 AM, Steven Robbins
reply@reply.github.com
wrote:

**Comment by kogir** [comment]
This was premature.

**Pull request closed without merging**
