### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by grumpydev**
As discussed via email.

I've broken every "good OSS contributor" rule in the book in tearing it apart and refactoring it, but I've tried to keep the same code style where I could :-)

There's now a .Core project that contains the compilers, caching mechanisms (none, in-memory, disk based) etc and a separate ASP.Net project that includes the module and handlers. I'm going to re-create the Nancy one, which should now be down to a handful of lines of code.

If you're happy with the approach I'll build the tests up - I generally hate test last development, but I wanted to get this working and over to you as quickly as I could :-)

### CODE REVIEW

**Comment by anaisbetts** [comment]
I'll try to review this right away!

**Comment by grumpydev** [comment]
The Nancy implementation is now much cleaner:

https://github.com/grumpydev/Nancy.SassAndCoffee/blob/master/Nancy.SassAndCoffee/Hooks.cs

**Comment by anaisbetts** [comment]
Alright, my plan is to put this into a remotely-tracked branch in my
repo, fix it up a bit, then rebase it onto master.

On Mon, Jul 4, 2011 at 10:58 PM, grumpydev
reply@reply.github.com
wrote:

**Comment by anaisbetts** [comment]
I'll try to do this ASAP, you put a ton of work into this and I want
it to hit the world as soon as possible!

**Comment by grumpydev** [comment]
It shouldn't need rebasing, unless you mean you're going to squish it.

What needs fixing up? I'm happy to do the fixup / squish and resend the pull .. happy to help :-)

**Comment by anaisbetts** [comment]
Nothing major, just some little things that I saw as I scanned through
it, and I have to get rid of all the newlines after the if's for my
own sanity :)  Actually, let's continue doing this the sloppy dev way
and I'll just party on master :)

On Tue, Jul 5, 2011 at 2:05 PM, grumpydev
reply@reply.github.com
wrote:

**Comment by grumpydev** [comment]
Isn't StyleCop compulsory at MS? ;-)

Happy to follow your lead.. It works at the moment, but it's definitely a bit of a rush job :-)

**Comment by anaisbetts** [comment]
It's compulsory in _DevDiv_ :)  My style is way closer to how the
Windows NT kernel code is written, officially referred to as "Cutler
Normal Form (CNF)"

On Tue, Jul 5, 2011 at 2:34 PM, grumpydev
reply@reply.github.com
wrote:

> Isn't StyleCop compulsory at MS? ;-)
> 
> Happy to follow your lead.. It works at the moment, but it's definitely a bit of a rush job :-)
>

**Pull request merged**
