### PR TITLE
V8Bridge: convert ansi string to utf-16

### PR DESCRIPTION
**Pull request by radiy**
fix no-ascii symbols corruption, send string in utf-16 instead of the ansi
i am not a c++ guy so my implementation could be ugly but it`s work

### CODE REVIEW

**Comment by anaisbetts** [comment]
Does this actually work? From reading the V8 code, I was under the impression that it didn't handle UTF-16 strings (wchar_t).

**Comment by radiy** [comment]
yes. I test it.
from v8.h line 1167

  /*\* Allocates a new string from utf16 data._/
  V8EXPORT static Local<String> New(const uint16_t_ data, int length = -1);

**Comment by radiy** [comment]
https://github.com/v8/v8/blob/master/include/v8.h#L1186

**Comment by anaisbetts** [comment]
Ok, awesome!

**Comment by emilingerslev** [comment]
I've had problems with double encoded utf-8, non-ascii characters like 'æøå' (danish characters). It seems this would fix it, but the V8-bridge in the source has not been compiled with these changes. Would you compile it so its possible just to run the install.ps1?
I've tried to compile the V8-bridge but it needs a lib_amd64\v8.lib. I guess that the compiled V8 library? I'm also not a c++ guy :)

**Comment by anaisbetts** [comment]
Yep, I'm going to do a release this week that will include this fix.  

## 

Paul Betts
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by emilingerslev** [comment]
Sounds good! Can't wait :)

**Comment by radiy** [comment]
v8-bridge compiled with my changes can be found at http://coffeemonitor.codeplex.com/SourceControl/network/Forks/radiy/NonAnsi/changeset/view/123445ea8f8a
in lib\V8Bridge folder

**Comment by emilingerslev** [comment]
Thanks :) I haven't tested it yet, but I will.

**Comment by anaisbetts** [comment]
Sorry for not including V8, it's too gigantic to check into source control

## 

Paul Betts

SENT FROM MY COMMODORE 64: RESPONSES MAY BE IN ALL CAPS

**Pull request merged**
