### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by mmanela**
I updated SassAndCoffee to also support TypeScript. I modeled the addition closely after how the CoffeeScript classes function.

One caveat is that the TypeScript compiler doesn't have a "bare" mode like the CoffeeScript one does. When bare is requested I just ignore it and return the normal typescript output.

### CODE REVIEW

**Comment by anaisbetts** [comment]
Cool! I'll have a look at this at the weekend

**Comment by anaisbetts** [comment]
Hi @mmanela, I'm not really maintaining this anymore. You seem interested though, so you've got commit access now, go ahead and merge this, but try to keep the style consistent.

**Comment by anaisbetts** [comment]
Feel free to merge the other pull requests too if they look good

**Comment by nathanpalmer** [comment]
@xpaulbettsx Any chance I can get commit support? I had to pull this in explicitly in HotGlue. I'd rather just have it part of the main build.

**Comment by anaisbetts** [comment]
@nathanpalmer You've got it.

**Comment by nathanpalmer** [comment]
Thanks @xpaulbettsx ! :+1:

**Pull request merged**
