### PR TITLE
Extracted config needed for compass

### PR DESCRIPTION
**Pull request by chrisortman**
I extracted out the parts that compass needs to be able to override. There is a static config class that I am planning to invoke in an App_Start compass file I'll ship with the nuget.

Trickiest part left is going to be figuring out where these ruby scripts are when running from the web app (up till now i have just been hard coding paths)

I may wind up creating an App_Ruby folder and copying the gems to that...would also let dynamic compilation happen on a deployed site...although i don't see myself using that very often.

On a side note, something understands App_Ruby and automatically spins up IR and requires / invokes some scripts might be neat, not sure what that would be used for though.

cheers

### CODE REVIEW

**Comment by anaisbetts** [comment]
I'll take a look at the pull request as reference, but one of the goals of SassAndCoffee is that it doesn't require any Ruby install.  I still think that getting Compass into SassAndCoffee is doable, and it would be awesome to be able to add Compass support

**Comment by nikolawannabe** [comment]
Getting this to work with Compass would be awesome.  I use Sencha Touch, and this would let us make crazy on the fly style changes to the mobile app I'm working on.

**Comment by anaisbetts** [comment]
Compass support is _the_ next feature I'm doing, but it's a fairly involved hack

## 

Paul Betts

SENT FROM MY COMMODORE 64: RESPONSES MAY BE IN ALL CAPS

**Comment by chrisortman** [comment]
Is it a requirement then that Compass work without having to have the ruby scripts and compass templates physically on the file system (like you have done with the existing ruby scripts)?

This all works without requiring Ruby to be installed, the biggest downside is that i have all the ruby code sitting in the nuget package so that just becomes a lot of artifacts to copy for deployment.

Did you find any noticeable perf difference between cat'ing all the ruby script into one file vs just embedding each item?

**Comment by anaisbetts** [comment]
The Ruby scripts, yes - but we'll probably end up installing the Compass templates in their project.  

The catting is solely to make the deployment bits easier, I don't care about it from a perf perspective. The critical thing that I'm going for is ease of use - if any feature adds a step to "1: Add NuGet package, 2: You're good to go", that's no good. 

Is there a good place to put those Compass scripts though that is easily discoverable in deployment? Remember, that the NuGet packages folder doesn't get deployed afaik, only referenced binaries do, so you can't put a bunch of Ruby scripts in the NuGet package and reference them from there. 

I know this post sounds negative - I totally want Compass to be part of S&C and it's next on my list, but ease of use and "It Just Works"'ness are my #1 goal with this project.

**Comment by chrisortman** [comment]
To make them discoverable during deployment they'll have to go in the
web project and get marked as content.

Sent from my iPhone

On Jul 18, 2011, at 3:51 PM, xpaulbettsx
reply@reply.github.com
wrote:

**Comment by mattpenner** [comment]
Any recent work on this?  I also am updating an MVC3/jqTouch app that now uses SASS and Compass.  Would love to be able to integrate it with this.  I don't work in Ruby but if either of you could provide a few steps on what is required to setup the Pull Chris created I'd really appreciate it.

**Comment by Meligy** [comment]
Is it OK to ask 2 years later about how this has gone?

Thanks a lot.

**Pull request closed without merging**
