### PR TITLE
Support using the JScript engine included with Windows

### PR DESCRIPTION
**Pull request by kogir**
Works nearly everywhere (save for Mono and Server Core editions).  Fast enough, with predictable life-cycle and memory usage.

### CODE REVIEW

**Comment by anaisbetts** [comment]
Let me test the perf on this - if it's fast enough, we'll just make this the primary engine and to hell with V8; if not, I'll make this the new fallback engine. Either way, this is awesome work, thanks a lot!

**Comment by kogir** [comment]
If it's fast enough and you want to go all the way, there's also my re-factor which separates Sass and CoffeeScript/Uglify and offloads all the caching and gzip-ing to IIS6/7:

https://github.com/kogir/SassAndCoffee/tree/refactor

**Comment by anaisbetts** [comment]
> If it's fast enough and you want to go all the way, there's also my
> re-factor which separates Sass and CoffeeScript/Uglify and offloads all the
> caching and gzip-ing to IIS6/7:

Thanks for doing all of this awesome work - I merged your refactor branch and
added you to the main repo. 

Feel free to just commit directly if it's a small change, if you want to do
something more crazy, put it on a branch and open a pull request (you can open
PRs between branches in the same repo, you don't have to fork into your own
copy)

## 

Paul Betts paul@paulbetts.org

**Comment by kogir** [comment]
Thanks for the vote of confidence.  The refactor branch wasn't quite ready for you to take yet, so I'll work on fixing the NuGet packaging (which I broke) and some of the cache settings in the next few days.

**Pull request merged**
